#!/usr/bin/env python3

import rospy
import numpy as np
from sensor_msgs.msg import Image
from cv_bridge import CvBridge
import cv2

  

class ImageSubscriber:

    def __init__(self):

        rospy.init_node('image_subscriber', anonymous=True)
        self.sub = rospy.Subscriber('image_topic', Image, self.callback)
        self.bridge = CvBridge()

    def callback(self, data):
        cv_image = self.bridge.imgmsg_to_cv2(data, 'bgr8')
        cv2.waitKey(1)
        
    
if __name__ == '__main__':
    try:
      
        subscriber = ImageSubscriber()
        rospy.spin()

    except rospy.ROSInterruptException:
        pass
