// Generated by gencpp from file pack/sub_client.msg
// DO NOT EDIT!


#ifndef PACK_MESSAGE_SUB_CLIENT_H
#define PACK_MESSAGE_SUB_CLIENT_H

#include <ros/service_traits.h>


#include <pack/sub_clientRequest.h>
#include <pack/sub_clientResponse.h>


namespace pack
{

struct sub_client
{

typedef sub_clientRequest Request;
typedef sub_clientResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct sub_client
} // namespace pack


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::pack::sub_client > {
  static const char* value()
  {
    return "1ea84f917e2d4a57c4ac42667c785711";
  }

  static const char* value(const ::pack::sub_client&) { return value(); }
};

template<>
struct DataType< ::pack::sub_client > {
  static const char* value()
  {
    return "pack/sub_client";
  }

  static const char* value(const ::pack::sub_client&) { return value(); }
};


// service_traits::MD5Sum< ::pack::sub_clientRequest> should match
// service_traits::MD5Sum< ::pack::sub_client >
template<>
struct MD5Sum< ::pack::sub_clientRequest>
{
  static const char* value()
  {
    return MD5Sum< ::pack::sub_client >::value();
  }
  static const char* value(const ::pack::sub_clientRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::pack::sub_clientRequest> should match
// service_traits::DataType< ::pack::sub_client >
template<>
struct DataType< ::pack::sub_clientRequest>
{
  static const char* value()
  {
    return DataType< ::pack::sub_client >::value();
  }
  static const char* value(const ::pack::sub_clientRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::pack::sub_clientResponse> should match
// service_traits::MD5Sum< ::pack::sub_client >
template<>
struct MD5Sum< ::pack::sub_clientResponse>
{
  static const char* value()
  {
    return MD5Sum< ::pack::sub_client >::value();
  }
  static const char* value(const ::pack::sub_clientResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::pack::sub_clientResponse> should match
// service_traits::DataType< ::pack::sub_client >
template<>
struct DataType< ::pack::sub_clientResponse>
{
  static const char* value()
  {
    return DataType< ::pack::sub_client >::value();
  }
  static const char* value(const ::pack::sub_clientResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // PACK_MESSAGE_SUB_CLIENT_H
