// Generated by gencpp from file pack/sub_clientRequest.msg
// DO NOT EDIT!


#ifndef PACK_MESSAGE_SUB_CLIENTREQUEST_H
#define PACK_MESSAGE_SUB_CLIENTREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <sensor_msgs/Image.h>

namespace pack
{
template <class ContainerAllocator>
struct sub_clientRequest_
{
  typedef sub_clientRequest_<ContainerAllocator> Type;

  sub_clientRequest_()
    : imgs()  {
    }
  sub_clientRequest_(const ContainerAllocator& _alloc)
    : imgs(_alloc)  {
  (void)_alloc;
    }



   typedef  ::sensor_msgs::Image_<ContainerAllocator>  _imgs_type;
  _imgs_type imgs;





  typedef boost::shared_ptr< ::pack::sub_clientRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::pack::sub_clientRequest_<ContainerAllocator> const> ConstPtr;

}; // struct sub_clientRequest_

typedef ::pack::sub_clientRequest_<std::allocator<void> > sub_clientRequest;

typedef boost::shared_ptr< ::pack::sub_clientRequest > sub_clientRequestPtr;
typedef boost::shared_ptr< ::pack::sub_clientRequest const> sub_clientRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::pack::sub_clientRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::pack::sub_clientRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::pack::sub_clientRequest_<ContainerAllocator1> & lhs, const ::pack::sub_clientRequest_<ContainerAllocator2> & rhs)
{
  return lhs.imgs == rhs.imgs;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::pack::sub_clientRequest_<ContainerAllocator1> & lhs, const ::pack::sub_clientRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace pack

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::pack::sub_clientRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::pack::sub_clientRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::pack::sub_clientRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::pack::sub_clientRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::pack::sub_clientRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::pack::sub_clientRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::pack::sub_clientRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "53bf267f7fc468272db35c5d679ee040";
  }

  static const char* value(const ::pack::sub_clientRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x53bf267f7fc46827ULL;
  static const uint64_t static_value2 = 0x2db35c5d679ee040ULL;
};

template<class ContainerAllocator>
struct DataType< ::pack::sub_clientRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "pack/sub_clientRequest";
  }

  static const char* value(const ::pack::sub_clientRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::pack::sub_clientRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "sensor_msgs/Image imgs\n"
"\n"
"================================================================================\n"
"MSG: sensor_msgs/Image\n"
"# This message contains an uncompressed image\n"
"# (0, 0) is at top-left corner of image\n"
"#\n"
"\n"
"Header header        # Header timestamp should be acquisition time of image\n"
"                     # Header frame_id should be optical frame of camera\n"
"                     # origin of frame should be optical center of camera\n"
"                     # +x should point to the right in the image\n"
"                     # +y should point down in the image\n"
"                     # +z should point into to plane of the image\n"
"                     # If the frame_id here and the frame_id of the CameraInfo\n"
"                     # message associated with the image conflict\n"
"                     # the behavior is undefined\n"
"\n"
"uint32 height         # image height, that is, number of rows\n"
"uint32 width          # image width, that is, number of columns\n"
"\n"
"# The legal values for encoding are in file src/image_encodings.cpp\n"
"# If you want to standardize a new string format, join\n"
"# ros-users@lists.sourceforge.net and send an email proposing a new encoding.\n"
"\n"
"string encoding       # Encoding of pixels -- channel meaning, ordering, size\n"
"                      # taken from the list of strings in include/sensor_msgs/image_encodings.h\n"
"\n"
"uint8 is_bigendian    # is this data bigendian?\n"
"uint32 step           # Full row length in bytes\n"
"uint8[] data          # actual matrix data, size is (step * rows)\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
;
  }

  static const char* value(const ::pack::sub_clientRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::pack::sub_clientRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.imgs);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct sub_clientRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::pack::sub_clientRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::pack::sub_clientRequest_<ContainerAllocator>& v)
  {
    s << indent << "imgs: ";
    s << std::endl;
    Printer< ::sensor_msgs::Image_<ContainerAllocator> >::stream(s, indent + "  ", v.imgs);
  }
};

} // namespace message_operations
} // namespace ros

#endif // PACK_MESSAGE_SUB_CLIENTREQUEST_H
